version: "3.8"

services:
  postgres:
    container_name: stock_wise_postgres_container
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stockwisedb
    volumes:
      - stock_wise_pg_data:/bitnami/postgresql

volumes:
  stock_wise_pg_data:
